### PR TITLE
feature: adds hero section on the landing page

### PR DESCRIPTION
**Pull request by SatyaRajAwasth1**
Part of #3 

image

### CODE REVIEW

**Comment by SatyaRajAwasth1** [comment]
Join global network... or Meet global... what would be good @Abhilekhgautam @rk-marseni ?

**Comment by mukezhz** [comment]
@SatyaRajAwasth1 I think its all about NCIT alumi website 🤔

maybe we should focus just on NCIT what do you think?

**Review by openrijal — APPROVED** [review]

**Comment by rk-marseni** [comment]
> Join global network... or Meet global... what would be good @Abhilekhgautam @rk-marseni ?

My preference is "**Meet a global network**" because our aim is to build **a global network of NCIT alumni**.

**Comment by openrijal** [comment]
@SatyaRajAwasth1 

# Stay Connected, Build Networks

Join the global NCIT Alumnus as they share their journeys, profiles and experiences creating opportunities together.

Submit Your Profile  |  Explore Alumni



Something like this, maybe? But yeah just NCIT, not NOSK.

**Comment by SatyaRajAwasth1** [comment]
> @SatyaRajAwasth1
> # Stay Connected, Build Networks
> 
> Join the global NCIT Alumnus as they share their journeys, profiles and experiences creating opportunities together.
> 
> Submit Your Profile | Explore Alumni
> 
> Something like this, maybe? But yeah just NCIT, not NOSK.

Fine with NCIT only. Should I consider changing the title line and sub-title line? 
@openrijal 

image

**Comment by SatyaRajAwasth1** [comment]
ammended over the same commit.

Here is how it looks now @mukezhz @openrijal 

image

**Review by mukezhz — APPROVED** [review]
LGTM 🔥

**Pull request merged**
